version: '2'

services:
  webserver:
    network_mode: bridge
    image: quangdinh/php7-api-standard:1.1.2
    container_name: nft-generator # Change with Project ID
    environment:
      docker: "true"
    ports:
      - "8080:80"
      - "44300:443"
    volumes:
      - .:/var/www